version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    container_name: laravel_app
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
      - ./docker/volumes/postgres_data:/var/lib/postgresql/data
      - ./docker/volumes/minio_data:/data
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel_app
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=${DB_PASSWORD:-Strong!PgPass123}
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET=${MINIO_SECRET_KEY:-StrongMinioSecret123!}
      - MINIO_BUCKET=laravel-app
      - MINIO_REGION=sa-east-1
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=app-person_prod
      - POSTGRES_USER=laravel_prod_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:c}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/conf:/etc/postgresql
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel_user -d laravel_app"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  minio:
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    container_name: minio_storage
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-StrongMinioSecret123!}
      - MINIO_REGION=sa-east-1
    volumes:
      - minio_data:/data
      - ./docker/minio/config:/root/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/docker/volumes/postgres_data
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/docker/volumes/minio_data